version: '2'
services:
    jhipsterprova1-app:
        image: jhipsterprova1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterprova1-mysql:3306/jhipsterprova1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterprova1-mysql:
        extends:
            file: mysql.yml
            service: jhipsterprova1-mysql
